[package]
name = "rust-lexer"
version = "0.1.0"
authors = ["fagel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cow-rc-str = "0.1.0"
